backend:
  name: git-gateway
  branch: main

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "index"
    label: "Home Page Content"
    files:
      - file: "public/cmscontent/index.md"
        label: "Index Markdown"
        name: "index"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }